#!/bin/bash

check_file () {
  # Check if the output data file already exists
  if [ -f "$1" ]; then
    # If it does, delete it
    rm $1
  fi
}

run_program () {
  check_file $1.class
  javac $1.java
  java $1.java $2
}



# Function to validate ISO 4217 currency code format
validate_code () {
  local code_regex="^[A-Z]{3}$"

  if [[ $1 =~ $code_regex ]]; then
    return 0
  else
    echo "Invalid currency code: $1. Expected format: Three uppercase letters (ISO 4217)." >&2
    exit 1
  fi
}

# Define a function to check the code parameter
check_code () {
  case $1 in
    --code=*)
      # Extract the code part from the parameter value
      local code="${1#*=}"
      validate_code $code
      ;;
    *) echo "Invalid parameter: $1" >&2 # Print error message and exit if incorrect
       exit 1 ;;
  esac
}

# Define a function to check the date parameter
check_date () {
  # Regular expression to match the date format "YYYY-MM-DD"
  local date_regex="^[0-9]{4}-[0-9]{2}-[0-9]{2}$"

  case $1 in
    --date=*)
      # Extract the date part from the parameter value
      local date="${1#*=}"

      if [[ $date =~ $date_regex ]]; then
        # Date format matches the expected pattern
        return 0
      else
        # Date format does not match the expected pattern
        echo "Invalid date format: $date. Expected format: YYYY-MM-DD" >&2
        exit 1
      fi
      ;;
    "")
      ;; # Do nothing if empty
    *)
      echo "Invalid parameter: $1" >&2 # Print error message and exit if incorrect
      exit 1 ;;
  esac
}

# Function to display help info
print_help () {
  echo -e "Интерфейс: currency_rates --code=USD --date=2022-10-08\n"
  echo "Описание параметров:"
  echo "* code - код валюты в формате ISO 4217"
  echo -e "* date - дата в формате YYYY-MM-DD\n"
  echo "Вывод: USD (Доллар США): 61,2475"
}

# Check if there are no launch parameters
if [ $# -eq 0 ]; then
  echo "No launch parameters!"
  exit 1
fi

# Check if the script was launched with the -h parameter
if [ "$1" = "-h" ]; then
  print_help
  exit 0
fi

code=$1
date=$2

# Call the functions to check the parameters
check_code $code
check_date $date

# Remove the --code= and --date= parts from the parameters
code=${code#*=}
date=${date#*=}

./curl.sh $date

main_class=src/main/java/com/currency_tracker/App

run_program $main_class $code

exit 0
